name: dime_flutter
description: Flutter support for Dime dependency injection. Will provide scoped widgets and
  helping methods to use Dime with in Flutter codebase.
version: 0.0.1-dev
homepage: https://github.com/magillus/dart_dime
author: Mateusz Perlak <mati.akip@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dime: ^0.3.0
  fimber: ^0.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
