name: dime_flutter
description: Flutter support for Dime dependency injection. Will provide scoped widgets and
  helping methods to use Dime with in Flutter codebase.
version: 0.5.0
homepage: https://github.com/magillus/dart_dime

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dime: ^0.5.0
  fimber: ^0.7.0

dev_dependencies:
  test: '^1.24.1'
  flutter_lints: '^2.0.0'

flutter:
