name: dime
description: Dime is Dependency getion for Dart, allows to define modules with signle/creator inejction factories, allows String tagging and simple Scope tree.
version: 0.3.0
homepage: https://github.com/magillus/dart_dime
author: Mateusz Perlak <mati.akip@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  fimber: ^0.1.11 # temporary -todo remove from final in RC

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

