name: dime
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/magillus/dart_dime
author: Mateusz Perlak <mati.akip@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  fimber: ^0.1.11 # temporary

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

